
site_name: AA191A-Web Development and GIS for Social Change
repo_url: https://github.com/albertkun/22S-ASIAAM-191A/

theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light-blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode  
  font:
    text: Arial
  favicon: etc/media/favicon.png
  logo: etc/media/favicon.png
  name: material
  custom_dir: overrides
  features:
      - navigation.instant
      - navigation.tabs
      - content.code.annotate
      - search.highlight
      - toc.integrate
      # - navigation.indexes
      - navigation.top
      - search.suggest
      
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
    - pymdownx.highlight:
        linenums: true
    - pymdownx.superfences
    - pymdownx.magiclink
    - smarty
    - footnotes
    - meta
    - pymdownx.keys
    - toc:
        permalink: True
        toc_depth: 2
    - sane_lists
    - admonition
    - footnotes
    - attr_list
    
extra_javascript:
  # - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - etc/js/tables.js
  - etc/js/extra.js
extra_css:
  - etc/css/extra.css

edit_uri: edit/dev/docs/
plugins:
  - git-revision-date
  - autorefs
  - table-reader
  - tags
  - macros
  - awesome-pages:
      collapse_single_pages: true
  - search:
      lang: en
  # - htmlproofer
      # raise_error: True
  - awesome-pages
  - macros
  - encryptcontent:
      title_prefix: '🔒'
      # global_password: !ENV ASIA_191_PASS
      # password_button: True      
      encrypted_something:
          mkdocs-encrypted-toc: [nav, class]
          mkdocs-encrypted-footer: [div, id]
          mkdocs-encrypted-footer-meta: [div, id]